apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: echoserver-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echoserver
      version: v2
  template:
    metadata:
      labels:
        app: echoserver
        version: v2
    spec:
      containers:
      - name: http-svc
        image: gcr.io/google-containers/echoserver:1.10
        ports:
        - containerPort: 8080
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            cpu: "0.5"
            memory: 128M
          limits:
            cpu: "0.5"
            memory: 128M
